/**
 * Conceptual data model — NOT a finalized backend contract.
 * Fields here are placeholders for UI development against mock data.
 * When the real /api/analyze response shape is known, update this file
 * to match it exactly rather than adding fields speculatively elsewhere.
 */

export type AnalysisStatus = "QUEUED" | "PROCESSING" | "COMPLETED" | "FAILED";

export type ProcessingStage =
  | "UPLOAD"
  | "PREPROCESSING"
  | "CATNET"
  | "NARRATIVE"
  | "REPORT";

export interface CatNetEvidence {
  /** URL to the heatmap image produced by CAT-Net localization. */
  heatmapUrl: string;
  /** URL to a backend-composited original+heatmap overlay, if the backend provides one. */
  overlayUrl?: string;
  /** Whether CAT-Net found any localized evidence at all — omitted when the backend doesn't report it. */
  hasEvidence?: boolean;
}

export interface NarrativeEvidence {
  /** Free-text explanation generated by the LLM from the CAT-Net evidence — not a verdict. */
  summary: string;
}

export interface AnalysisPage {
  pageNumber: number;
  originalImageUrl: string;
  catnet: CatNetEvidence;
}

export interface Analysis {
  id: string;
  documentName: string;
  documentType: string;
  pageCount: number;
  status: AnalysisStatus;
  stage?: ProcessingStage;
  createdAt: string;
  pages: AnalysisPage[];
  narrative?: NarrativeEvidence;
  /** Why the narrative step produced nothing, when it was attempted and failed. */
  narrativeError?: string;
  error?: string;
}
